"""initial_tables

Revision ID: e2e1c4519c86
Revises: 
Create Date: 2026-03-15 20:05:59.064533
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2e1c4519c86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Створюємо enum типи через raw SQL
    op.execute("CREATE TYPE user_role AS ENUM ('USER', 'ADMIN')")
    op.execute("CREATE TYPE chat_type AS ENUM ('TEXT', 'VOICE')")
    op.execute("CREATE TYPE conversation_status AS ENUM ('ACTIVE', 'ENDED')")
    op.execute("CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY')")
    op.execute("CREATE TYPE communication_style AS ENUM ('ANALYTICAL', 'FRIENDLY', 'BALANCED')")
    op.execute("CREATE TYPE message_sender AS ENUM ('USER', 'BOT')")
    op.execute("CREATE TYPE crisis_level AS ENUM ('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')")
    op.execute("CREATE TYPE knowledge_category AS ENUM ('CBT', 'ACT', 'DBT', 'CRISIS', 'SELF_HELP', 'ARTICLE', 'BOOK', 'OTHER')")
    op.execute("CREATE TYPE knowledge_status AS ENUM ('ACTIVE', 'PROCESSING', 'ARCHIVED', 'ERROR')")

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='user_role', create_type=False), server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('chat_type', postgresql.ENUM('TEXT', 'VOICE', name='chat_type', create_type=False), server_default='TEXT', nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'ENDED', name='conversation_status', create_type=False), server_default='ACTIVE', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True, comment="Короткий висновок розмови для контекстної пам'яті"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('emotion_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False, comment='Дата запису'),
    sa.Column('emoji', sa.String(length=10), nullable=True, comment='Емодзі емоції за день'),
    sa.Column('user_description', sa.Text(), nullable=True, comment='Опис стану від користувача'),
    sa.Column('bot_description', sa.Text(), nullable=True, comment='Опис стану згенерований ботом'),
    sa.Column('emotion_tags', postgresql.ARRAY(sa.String(length=50)), nullable=True, comment='Теги емоцій: стрес, щастя, злість, тривога тощо'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_entries_entry_date'), 'emotion_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_emotion_entries_id'), 'emotion_entries', ['id'], unique=False)
    op.create_index(op.f('ix_emotion_entries_user_id'), 'emotion_entries', ['user_id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', postgresql.ENUM('CBT', 'ACT', 'DBT', 'CRISIS', 'SELF_HELP', 'ARTICLE', 'BOOK', 'OTHER', name='knowledge_category', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=True, comment='Повний текст матеріалу'),
    sa.Column('source', sa.String(length=500), nullable=True, comment='Джерело матеріалу (URL, назва книги)'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='Шлях до завантаженого файлу'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PROCESSING', 'ARCHIVED', 'ERROR', name='knowledge_status', create_type=False), server_default='PROCESSING', nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='Кількість чанків після розбиття'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender', create_type=False), nullable=True),
    sa.Column('communication_style', postgresql.ENUM('ANALYTICAL', 'FRIENDLY', 'BALANCED', name='communication_style', create_type=False), server_default='BALANCED', nullable=False),
    sa.Column('life_area', sa.Text(), nullable=True, comment='Сфера життя для покращення'),
    sa.Column('concern', sa.Text(), nullable=True, comment='Що найбільше бентежить'),
    sa.Column('works_with_psychologist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('survey_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender', postgresql.ENUM('USER', 'BOT', name='message_sender', create_type=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('emotion_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Результат аналізу емоцій повідомлення'),
    sa.Column('crisis_level', postgresql.ENUM('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='crisis_level', create_type=False), server_default='NONE', nullable=False),
    sa.Column('is_crisis', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_emotion_entries_user_id'), table_name='emotion_entries')
    op.drop_index(op.f('ix_emotion_entries_id'), table_name='emotion_entries')
    op.drop_index(op.f('ix_emotion_entries_entry_date'), table_name='emotion_entries')
    op.drop_table('emotion_entries')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # Видаляємо enum типи
    op.execute("DROP TYPE IF EXISTS user_role")
    op.execute("DROP TYPE IF EXISTS chat_type")
    op.execute("DROP TYPE IF EXISTS conversation_status")
    op.execute("DROP TYPE IF EXISTS gender")
    op.execute("DROP TYPE IF EXISTS communication_style")
    op.execute("DROP TYPE IF EXISTS message_sender")
    op.execute("DROP TYPE IF EXISTS crisis_level")
    op.execute("DROP TYPE IF EXISTS knowledge_category")
    op.execute("DROP TYPE IF EXISTS knowledge_status")
    # ### end Alembic commands ###
